TRUNCATE TABLE B2C.PO_DISTRIBUTIONS_INTERFACE;
INSERT INTO B2C.PO_DISTRIBUTIONS_INTERFACE
WITH SMART_HEADER AS(
SELECT * FROM
(SELECT DENSE_RANK() OVER(PARTITION BY SUBSTR(H.PO_ID,1,9) ORDER BY H.PO_ID DESC) RNK,H.*,SL.PO_ID SL_PO_ID,SL.LINE_NUMBER SL_LINE_NUMBER,
SL.REQUESTOR_SHIPTO SL_REQUESTOR_SHIPTO,SL.NEED_BY_DATE SL_NEED_BY_DATE,SL.REQUESTOR_DELIVERTO SL_REQUESTOR_DELIVERTO, GL_SEG1_ENTITY,GL_SEG4_DEPARTMENT,
GL_SEG3_ACCOUNT,GL_SEG6_COUNTRY, GL_SEG7_APC,SL.LOCATION SL_LOCATION
FROM SMARTSTG.SMARTOUTBOUNDPOHEADER@SMART_DATA H INNER JOIN SMARTSTG.SMARTOUTBOUNDPOLINE@SMART_DATA SL ON H.PO_ID=SL.PO_ID
WHERE  H.WM_PROCESS_FLAG='C')
WHERE RNK=1) ,
RECEIPT AS (SELECT PO_HEADER_ID,PO_LINE_ID,SUM(PO_UNIT_PRICE*QUANTITY) AMOUNT_RECEIVED,SUM(QUANTITY) QUANTITY_RECEIVED
FROM APPS.RCV_TRANSACTIONS GROUP BY PO_HEADER_ID,PO_LINE_ID)
SELECT * FROM (SELECT DISTINCT
PDL.PO_DISTRIBUTION_ID AS INTERFACE_DISTRIBUTION_KEY,
PDL.LINE_LOCATION_ID   AS INTERFACE_LINE_LOCATION_KEY,
PDL.DISTRIBUTION_NUM   AS DISTRIBUTION_NUM, 
APPS.B2C_FNS_PKG.B2C_value_mapping('PURCHASE ORDERS', 'LOCATIONS',PH.SL_LOCATION) AS DELIVER_TO_LOCATION , 
REGEXP_REPLACE(REPLACE(CASE  WHEN SL_REQUESTOR_DELIVERTO LIKE '%,%' OR SL_REQUESTOR_DELIVERTO LIKE '%"%' 
THEN '"'|| SUBSTR(REPLACE(SL_REQUESTOR_DELIVERTO, '"', ''''), 1) || '"'
                   ELSE SUBSTR(SL_REQUESTOR_DELIVERTO, 1) END, CHR(10), ''
    ),'/','') AS  DELIVER_TO_PERSON_FULL_NAME , 
NULL AS DESTINATION_SUBINVENTORY,
SUM(PL.QUANTITY*PL.UNIT_PRICE) OVER(PARTITION BY PL.PO_HEADER_ID,PL.PO_LINE_ID)-NVL(REC.AMOUNT_RECEIVED,0) AS AMOUNT  ,
SUM(PDL.QUANTITY_ORDERED) OVER(PARTITION BY PL.PO_HEADER_ID,PL.PO_LINE_ID)-NVL(REC.QUANTITY_RECEIVED,0)  AS QUANTITY_ORDERED,   
APPS.B2C_FNS_PKG.B2C_value_mapping('General Ledger', 'MOGL_ENTITY', PH.GL_SEG1_ENTITY) CHARGE_ACCOUNT_segment1,  -- LE segment
CASE WHEN PH.GL_SEG3_ACCOUNT LIKE '8%' THEN
APPS.B2C_FNS_PKG.B2C_value_mapping('General Ledger', 'MOGL_DEPT', PH.GL_SEG4_DEPARTMENT) ELSE TO_CHAR('00000') END AS CHARGE_ACCOUNT_segment2,-- Dept segment
APPS.B2C_FNS_PKG.B2C_value_mapping('General Ledger', 'MOGL_ACCOUNT', PH.GL_SEG3_ACCOUNT) CHARGE_ACCOUNT_segment3, -- Account segment
APPS.B2C_FNS_PKG.B2C_value_mapping('General Ledger', 'MOGL_APC', PH.GL_SEG7_APC) CHARGE_ACCOUNT_segment4,     -- Line of Business Segment
APPS.B2C_FNS_PKG.B2C_value_mapping('General Ledger', 'MOGL_COUNTRY', PH.GL_SEG6_COUNTRY) CHARGE_ACCOUNT_segment5, -- Region segment
TO_CHAR('0000') AS CHARGE_ACCOUNT_segment6,  -- Intercompany segment
TO_CHAR('00000') AS CHARGE_ACCOUNT_segment7,
TO_CHAR('00000') AS CHARGE_ACCOUNT_segment8,
NULL AS CHARGE_ACCOUNT_SEGMENT9,
NULL AS CHARGE_ACCOUNT_SEGMENT10,
NULL AS CHARGE_ACCOUNT_SEGMENT11,
NULL AS CHARGE_ACCOUNT_SEGMENT12,
NULL AS CHARGE_ACCOUNT_SEGMENT13,
NULL AS CHARGE_ACCOUNT_SEGMENT14,
NULL AS CHARGE_ACCOUNT_SEGMENT15,
NULL AS CHARGE_ACCOUNT_SEGMENT16,
NULL AS CHARGE_ACCOUNT_SEGMENT17,
NULL AS CHARGE_ACCOUNT_SEGMENT18,
NULL AS CHARGE_ACCOUNT_SEGMENT19,
NULL AS CHARGE_ACCOUNT_SEGMENT20,
NULL AS CHARGE_ACCOUNT_SEGMENT21,
NULL AS CHARGE_ACCOUNT_SEGMENT22,
NULL AS CHARGE_ACCOUNT_SEGMENT23,
NULL AS CHARGE_ACCOUNT_SEGMENT24,
NULL AS CHARGE_ACCOUNT_SEGMENT25,
NULL AS CHARGE_ACCOUNT_SEGMENT26,
NULL AS CHARGE_ACCOUNT_SEGMENT27,
NULL AS CHARGE_ACCOUNT_SEGMENT28,
NULL AS CHARGE_ACCOUNT_SEGMENT29,
NULL AS CHARGE_ACCOUNT_SEGMENT30,
PDL.DESTINATION_CONTEXT AS DESTINATION_CONTEXT,     
PPA.SEGMENT1 AS PROJECT,
PT.TASK_NUMBER AS TASK,
TO_CHAR(PDL.EXPENDITURE_ITEM_DATE,'YYYY/MM/DD') AS  PJC_EXPENDITURE_ITEM_DATE ,
APPS.B2C_FNS_PKG.B2C_value_mapping('Projects', 'EXPENDITURE_TYPE', PDL.EXPENDITURE_TYPE) AS XPENDITURE_TYPE,        
CASE WHEN TRIM(OU.NAME) IS NULL THEN NULL ELSE
'"' || APPS.B2C_FNS_PKG.B2C_value_mapping('Projects', 'ORGANIZATION_NAME', decode(ou.name, 'DEFAULT', '00000',
                                                                                             'UK Arris USD', 'UK Arris USD',
                                                                                             'Latens UK ARRIS', 'Latens UK ARRIS',
                                                                                             substr(ou.name, 1, 5))) || '"' END AS EXPENDITURE_ORGANIZATION,
NULL AS PJC_BILLABLE_FLAG,
NULL AS PJC_CAPITALIZABLE_FLAG,  
NULL AS PJC_WORK_TYPE,    
NULL AS PJC_RESERVED_ATTRIBUTE1, 
NULL AS PJC_RESERVED_ATTRIBUTE2,
NULL AS PJC_RESERVED_ATTRIBUTE3,
NULL AS PJC_RESERVED_ATTRIBUTE4,
NULL AS PJC_RESERVED_ATTRIBUTE5,
NULL AS PJC_RESERVED_ATTRIBUTE6,
NULL AS PJC_RESERVED_ATTRIBUTE7,
NULL AS PJC_RESERVED_ATTRIBUTE8,
NULL AS PJC_RESERVED_ATTRIBUTE9,
NULL AS PJC_RESERVED_ATTRIBUTE10, 
NULL AS PJC_USER_DEF_ATTRIBUTE1,
NULL AS PJC_USER_DEF_ATTRIBUTE2,
NULL AS PJC_USER_DEF_ATTRIBUTE3,
NULL AS PJC_USER_DEF_ATTRIBUTE4,
NULL AS PJC_USER_DEF_ATTRIBUTE5,
NULL AS PJC_USER_DEF_ATTRIBUTE6,
NULL AS PJC_USER_DEF_ATTRIBUTE7,
NULL AS PJC_USER_DEF_ATTRIBUTE8,
NULL AS PJC_USER_DEF_ATTRIBUTE9,
NULL AS PJC_USER_DEF_ATTRIBUTE10,
NVL(H.RATE,PH.CURRENCY_RATE) AS RATE,
TO_CHAR(NVL(H.RATE_DATE,PH.CURRENCY_RATE_DATE),'YYYY/MM/DD') AS RATE_DATE,
NULL AS ATTRIBUTE_CATEGORY,
PH.GL_SEG4_DEPARTMENT AS ATTRIBUTE1,
PH.GL_SEG3_ACCOUNT AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL  AS ATTRIBUTE10,
NULL  AS ATTRIBUTE11,
NULL  AS ATTRIBUTE12,
NULL  AS ATTRIBUTE13,
NULL  AS ATTRIBUTE14,
NULL  AS ATTRIBUTE15,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE18,
NULL AS ATTRIBUTE19,
NULL AS ATTRIBUTE20,
NULL AS ATTRIBUTE_DATE1,
NULL AS ATTRIBUTE_DATE2,
NULL AS ATTRIBUTE_DATE3,
NULL AS ATTRIBUTE_DATE4,
NULL AS ATTRIBUTE_DATE5,
NULL AS ATTRIBUTE_DATE6,
NULL AS ATTRIBUTE_DATE7,
NULL AS ATTRIBUTE_DATE8,
NULL AS ATTRIBUTE_DATE9,
NULL AS ATTRIBUTE_DATE10,
NULL AS ATTRIBUTE_NUMBER1,
NULL AS ATTRIBUTE_NUMBER2,
NULL AS ATTRIBUTE_NUMBER3,
NULL AS ATTRIBUTE_NUMBER4,
NULL AS ATTRIBUTE_NUMBER5,
NULL AS ATTRIBUTE_NUMBER6,
NULL AS ATTRIBUTE_NUMBER7,
NULL AS ATTRIBUTE_NUMBER8,
NULL AS ATTRIBUTE_NUMBER9,
NULL AS ATTRIBUTE_NUMBER10,
NULL AS ATTRIBUTE_TIMESTAMP1,
NULL AS ATTRIBUTE_TIMESTAMP2,
NULL AS ATTRIBUTE_TIMESTAMP3,
NULL AS ATTRIBUTE_TIMESTAMP4,
NULL AS ATTRIBUTE_TIMESTAMP5,
NULL AS ATTRIBUTE_TIMESTAMP6,
NULL AS ATTRIBUTE_TIMESTAMP7,
NULL AS ATTRIBUTE_TIMESTAMP8,
NULL AS ATTRIBUTE_TIMESTAMP9,
NULL AS ATTRIBUTE_TIMESTAMP10,
REGEXP_REPLACE(PH.REQUESTOR_EMAIL,' ','') AS DELIVER_TO_PERSON_EMAIL_ADDR,
NULL AS BUDGET_DATE ,
NULL AS PJC_CONTRACT_NUMBER,
NULL AS PJC_FUNDING_SOURCE,
SYSDATE AS CREATION_DATE,
'TR' AS CREATED_BY,
'N' AS PROCESS_FLAG    
FROM APPS.PO_DISTRIBUTIONS_ALL PDL
INNER JOIN APPS.PO_LINE_LOCATIONS_ALL PLLA ON PDL.LINE_LOCATION_ID =PLLA.LINE_LOCATION_ID
AND PDL.PO_HEADER_ID=PLLA.PO_HEADER_ID AND PDL.PO_LINE_ID=PLLA.PO_LINE_ID
INNER JOIN APPS.PO_LINES_ALL PL ON PL.PO_HEADER_ID = PLLA.PO_HEADER_ID AND PL.PO_LINE_ID =PLLA.PO_LINE_ID
INNER JOIN APPS.PO_HEADERS_ALL H ON H.PO_HEADER_ID = PL.PO_HEADER_ID
INNER JOIN SMART_HEADER PH ON SUBSTR(PH.PO_ID,1,9)=H.SEGMENT1 AND PH.SL_LINE_NUMBER=PL.LINE_NUM
--INNER JOIN B2C.B2C_P_VENDORS V ON V.VENDOR_ID=H.VENDOR_ID
INNER JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID
LEFT OUTER JOIN RECEIPT REC ON REC.PO_HEADER_ID=PL.PO_HEADER_ID AND REC.PO_LINE_ID=PL.PO_LINE_ID
--LEFT JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID
LEFT JOIN APPS.PO_VENDOR_SITES_ALL VS ON H.VENDOR_SITE_ID||H.VENDOR_ID=VS.VENDOR_SITE_ID||VS.VENDOR_ID
LEFT JOIN APPS.PA_PROJECTS_ALL PPA ON PPA.PROJECT_ID=PDL.PROJECT_ID
LEFT JOIN APPS.PA_TASKS PT ON PT.TASK_ID=PDL.TASK_ID AND PT.PROJECT_ID=PDL.PROJECT_ID
LEFT JOIN APPS.HR_ALL_ORGANIZATION_UNITS OU ON OU.ORGANIZATION_ID=PDL.EXPENDITURE_ORGANIZATION_ID
--LEFT JOIN APPS.GL_CODE_COMBINATIONS GC ON PDL.CODE_COMBINATION_ID=GC.CODE_COMBINATION_ID
WHERE NVL(H.CLOSED_CODE, '~') <> 'CLOSED'
AND PV.ENABLED_FLAG='Y'
AND PV.END_DATE_ACTIVE IS NULL
AND NVL(PV.VENDOR_TYPE_LOOKUP_CODE,'X') <> 'EXPENSERPT'
AND VS.INACTIVE_DATE IS NULL
AND NVL(VS.RFQ_ONLY_SITE_FLAG,'N')='N'
AND H.SEGMENT1 LIKE 'A%'
AND H.ORG_ID<>'24266'
--AND h.org_id in (667,25697,23352,24251,166,24246,206,25692,23507)
AND MONTHS_BETWEEN(SYSDATE,H.CREATION_DATE)<=18)
WHERE AMOUNT>0;​