TRUNCATE TABLE B2C.PO_HEADERS_INTERFACE;
INSERT INTO B2C.PO_HEADERS_INTERFACE
WITH SMART_HEADER AS(
SELECT * FROM
(SELECT DENSE_RANK() OVER(PARTITION BY SUBSTR(H.PO_ID,1,9) ORDER BY H.PO_ID DESC) RNK,H.*,SL.LINE_NUMBER SL_LINE_NUMBER
, SL.GL_SEG1_ENTITY,SL.REQUESTOR_SHIPTO SL_REQUESTOR_SHIPTO,SL.LOCATION SL_LOCATION    
FROM SMARTSTG.SMARTOUTBOUNDPOHEADER@SMART_DATA H INNER JOIN SMARTSTG.SMARTOUTBOUNDPOLINE@SMART_DATA SL ON H.PO_ID=SL.PO_ID
WHERE  H.WM_PROCESS_FLAG='C')
WHERE RNK=1),
RECEIPT AS (SELECT PO_HEADER_ID,PO_LINE_ID,SUM(PO_UNIT_PRICE*QUANTITY) QUANTITY_RECEIVED
FROM APPS.RCV_TRANSACTIONS GROUP BY PO_HEADER_ID,PO_LINE_ID)
SELECT distinct
H.PO_HEADER_ID AS INTERFACE_HEADER_KEY,
'ORIGINAL' AS ACTION,
TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) AS BATCH_ID  ,
NVL(H.INTERFACE_SOURCE_CODE,'SMART') AS INTERFACE_SOURCE_CODE,
'BYPASS'  AS APPROVAL_ACTION  ,
H.SEGMENT1 AS DOCUMENT_NUM  ,
H.TYPE_LOOKUP_CODE AS DOCUMENT_TYPE_CODE,
NULL AS STYLE_DISPLAY_NAME        ,
APPS.B2C_FNS_PKG.B2C_value_mapping('ALL', 'OPERATING_UNIT', OU.NAME) PRC_BU_NAME ,
APPS.B2C_FNS_PKG.B2C_value_mapping('ALL', 'OPERATING_UNIT', OU.NAME) REQ_BU_NAME ,
APPS.B2C_FNS_PKG.B2C_value_mapping('Projects', 'LEGAL_ENTITY', APPS.B2C_FNS_PKG.B2C_value_mapping('ALL', 'OPERATING_UNIT', OU.NAME)) AS SOLDTO_LE_NAME, 
APPS.B2C_FNS_PKG.B2C_value_mapping('ALL', 'OPERATING_UNIT', OU.NAME) AS BILLTO_BU_NAME     ,


PH.REQUESTOR_UNIQUENAME AS AGENT_NAME,              --('Underwood, Mark'  AS AGENT_NAME  ,)
H.CURRENCY_CODE AS CURRENCY_CODE    ,
NVL(H.RATE,PH.CURRENCY_RATE) AS RATE ,

(CASE WHEN H.RATE_TYPE IS NOT NULL THEN 'User'      --(H.RATE_TYPE AS RATE_TYPE,)
      	ELSE H.RATE_TYPE END) AS RATE_TYPE,
NULL AS RATE_DATE,				    --(TO_CHAR(NVL(H.RATE_DATE,PH.CURRENCY_RATE_DATE),'YYYY/MM/DD')  AS RATE_DATE   ,)			


REPLACE(CASE  WHEN H.COMMENTS LIKE '%,%' OR H.COMMENTS LIKE '%"%' THEN '"'|| SUBSTR(REPLACE(H.COMMENTS, '"', ''''), 1) || '"'
                   ELSE SUBSTR(H.COMMENTS, 1) END, CHR(10), ''
    ) AS COMMENTS  ,
PH.BILL_TO_LOCATION AS BILL_TO_LOCATION  ,
APPS.B2C_FNS_PKG.B2C_value_mapping('PURCHASE ORDERS', 'LOCATIONS',PH.SL_LOCATION) AS SHIP_TO_LOCATION      ,
REPLACE(CASE  WHEN PV.VENDOR_NAME LIKE '%,%'  THEN '"'|| SUBSTR(REPLACE(PV.VENDOR_NAME, '"', ''''), 1) || '"'
                   ELSE SUBSTR(PV.VENDOR_NAME, 1) END, CHR(10), ''
    ) AS VENDOR_NAME      ,
PV.SEGMENT1 AS VENDOR_NUM      ,
VS.VENDOR_SITE_CODE AS VENDOR_SITE     ,
CASE WHEN TRIM(UPPER(VC.FIRST_NAME||' '||VC.LAST_NAME)) IN ('NA','N/A',NULL) THEN NULL ELSE
REPLACE(CASE  WHEN VC.FIRST_NAME||' '||VC.LAST_NAME LIKE '%,%' OR VC.FIRST_NAME||' '||VC.LAST_NAME LIKE '%"%'
THEN '"'|| SUBSTR(REPLACE(VC.FIRST_NAME||' '||VC.LAST_NAME, '"', ''''), 1) || '"'
                   ELSE SUBSTR(VC.FIRST_NAME||' '||VC.LAST_NAME, 1) END, CHR(10), ''
    ) END AS VENDOR_CONTACT,
H.VENDOR_ORDER_NUM AS VENDOR_DOC_NUM    ,
APPS.B2C_FNS_PKG.B2C_value_mapping('Supplier Sites', 'FOB_LOOKUP_CODE', H.FOB_LOOKUP_CODE)  AS FOB,
NULL AS FREIGHT_CARRIER ,
H.FREIGHT_TERMS_LOOKUP_CODE AS FREIGHT_TERMS ,
DECODE(UPPER(H.PAY_ON_CODE),'RECEIPT','Y','N') AS PAY_ON_CODE ,
APPS.B2C_FNS_PKG.B2C_value_mapping('ALL', 'TERMS_NAME', AT.NAME) AS PAYMENT_TERMS     ,
NULL AS ORIGINATOR_ROLE ,
H.CHANGE_SUMMARY AS CHANGE_ORDER_DESC    ,
H.ACCEPTANCE_REQUIRED_FLAG  AS ACCEPTANCE_REQUIRED_FLAG ,
NULL AS ACCEPTANCE_WITHIN_DAYS      ,
(CASE WHEN NVL(VS.ATTRIBUTE1,PH.SUPPLIER_EMAIL) IS NOT NULL THEN 'EMAIL'
		WHEN NVL(VS.ATTRIBUTE1,PH.SUPPLIER_EMAIL) IS NULL AND VS.FAX IS NOT NULL THEN 'FAX' 
		ELSE 'NONE' END) AS SUPPLIER_NOTIF_METHOD,
(CASE WHEN NVL(VS.ATTRIBUTE1,PH.SUPPLIER_EMAIL) IS NULL AND VS.FAX IS NOT NULL THEN NVL2(VS.FAX_AREA_CODE,RTRIM(VS.FAX_AREA_CODE)||'-',NULL)||VS.FAX 
		ELSE NULL END) AS FAX,--FAX_AREA_CODE||VS.FAX AS FAX,
REGEXP_REPLACE(CASE WHEN NVL(VS.ATTRIBUTE1,PH.SUPPLIER_EMAIL) IS NOT NULL 
	THEN  (REPLACE(CASE  WHEN NVL(VS.ATTRIBUTE1,PH.SUPPLIER_EMAIL) LIKE '%,%' 
    THEN '"'|| SUBSTR(REPLACE(NVL(VS.ATTRIBUTE1,PH.SUPPLIER_EMAIL), '"', ''''), 1) || '"'
                  ELSE SUBSTR(NVL(VS.ATTRIBUTE1,PH.SUPPLIER_EMAIL), 1)
      END,
      CHR(10), ''
	       ))ELSE NULL END,' ','') AS EMAIL_ADDRESS ,
H.CONFIRMING_ORDER_FLAG AS CONFIRMING_ORDER_FLAG          ,
H.NOTE_TO_VENDOR AS NOTE_TO_VENDOR      ,
H.NOTE_TO_RECEIVER   AS NOTE_TO_RECEIVER  ,
NULL AS DEFAULT_TAXATION_COUNTRY      ,
NULL AS TAX_DOCUMENT_SUBTYPE      ,
NULL AS ATTRIBUTE_CATEGORY        ,
NULL AS ATTRIBUTE1   ,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE18,
NULL AS ATTRIBUTE19,
NULL AS ATTRIBUTE20,
NULL AS ATTRIBUTE_DATE1,
NULL AS ATTRIBUTE_DATE2,
NULL AS ATTRIBUTE_DATE3,
NULL AS ATTRIBUTE_DATE4,
NULL AS ATTRIBUTE_DATE5,
NULL AS ATTRIBUTE_DATE6,
NULL AS ATTRIBUTE_DATE7,
NULL AS ATTRIBUTE_DATE8,
NULL AS ATTRIBUTE_DATE9,
NULL AS ATTRIBUTE_DATE10,
NULL AS ATTRIBUTE_NUMBER1,
NULL AS ATTRIBUTE_NUMBER2,
NULL AS ATTRIBUTE_NUMBER3,
NULL AS ATTRIBUTE_NUMBER4,
NULL AS ATTRIBUTE_NUMBER5,
NULL AS ATTRIBUTE_NUMBER6,
NULL AS ATTRIBUTE_NUMBER7,
NULL AS ATTRIBUTE_NUMBER8,
NULL AS ATTRIBUTE_NUMBER9,
NULL AS ATTRIBUTE_NUMBER10,
NULL AS ATTRIBUTE_TIMESTAMP1,
NULL AS ATTRIBUTE_TIMESTAMP2,
NULL AS ATTRIBUTE_TIMESTAMP3,
NULL AS ATTRIBUTE_TIMESTAMP4,
NULL AS ATTRIBUTE_TIMESTAMP5,
NULL AS ATTRIBUTE_TIMESTAMP6,
NULL AS ATTRIBUTE_TIMESTAMP7,
NULL AS ATTRIBUTE_TIMESTAMP8,
NULL AS ATTRIBUTE_TIMESTAMP9,
NULL AS ATTRIBUTE_TIMESTAMP10,
PH.REQUESTOR_EMAIL  AS AGENT_EMAIL_ADDRESS  ,
NULL AS MODE_OF_TRANSPORT  ,
NULL AS SERVICE_LEVEL    ,
NULL AS FIRST_PTY_REG_NUM      ,
NULL AS THIRD_PTY_REG_NUM  ,
NULL AS BUYER_MANAGED_TRANSPORT_FLAG,
SYSDATE AS CREATION_DATE,
'TR' AS CREATED_BY,
'N' AS PROCESS_FLAG
FROM
APPS.PO_HEADERS_ALL H
INNER JOIN SMART_HEADER PH ON H.SEGMENT1=SUBSTR(PH.PO_ID,1,9)
INNER JOIN APPS.PO_LINES_ALL PL ON H.PO_HEADER_ID=PL.PO_HEADER_ID AND PH.SL_LINE_NUMBER=PL.LINE_NUM
--INNER JOIN B2C.B2C_P_VENDORS V ON V.VENDOR_ID=H.VENDOR_ID
INNER JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID
LEFT OUTER JOIN RECEIPT REC ON REC.PO_HEADER_ID=PL.PO_HEADER_ID and rec.po_line_id=pl.po_line_id
LEFT JOIN APPS.HR_ALL_ORGANIZATION_UNITS OU ON H.ORG_ID=OU.ORGANIZATION_ID
--LEFT JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID
LEFT JOIN APPS.PO_VENDOR_SITES_ALL VS ON H.VENDOR_SITE_ID||H.VENDOR_ID=VS.VENDOR_SITE_ID||VS.VENDOR_ID
LEFT JOIN APPS.AP_TERMS AT ON H.TERMS_ID=AT.TERM_ID 
LEFT JOIN APPS.PO_VENDOR_CONTACTS VC ON VC.VENDOR_CONTACT_ID=H.VENDOR_CONTACT_ID
WHERE NVL(H.CLOSED_CODE, '~') <> 'CLOSED'
AND PV.ENABLED_FLAG='Y'
    AND PV.END_DATE_ACTIVE IS NULL
    AND NVL(PV.VENDOR_TYPE_LOOKUP_CODE,'X') <> 'EXPENSERPT'
    AND VS.INACTIVE_DATE IS NULL
    AND NVL(VS.RFQ_ONLY_SITE_FLAG,'N')='N'
    AND H.SEGMENT1 LIKE 'A%'
    AND H.ORG_ID <>'24266'
   -- AND H.ORG_ID in ( 667,25697,23352,24251,166,24246,206,25692,23507)
AND PL.QUANTITY*PL.UNIT_PRICE-NVL(REC.QUANTITY_RECEIVED,0)>0
AND MONTHS_BETWEEN(SYSDATE,H.CREATION_DATE)<=18;