TRUNCATE TABLE B2C.PO_LINES_INTERFACE;
INSERT INTO B2C.PO_LINES_INTERFACE
WITH SMART_HEADER AS(
SELECT * FROM
(SELECT DENSE_RANK() OVER(PARTITION BY SUBSTR(H.PO_ID,1,9) ORDER BY H.PO_ID DESC) RNK,H.*,SL.PO_ID SL_PO_ID,SL.LINE_NUMBER SL_LINE_NUMBER
,SL.UNSPSC_NAME
FROM SMARTSTG.SMARTOUTBOUNDPOHEADER@SMART_DATA H INNER JOIN SMARTSTG.SMARTOUTBOUNDPOLINE@SMART_DATA SL ON H.PO_ID=SL.PO_ID
WHERE  H.WM_PROCESS_FLAG='C')
WHERE RNK=1),
RECEIPT AS (SELECT PO_HEADER_ID,PO_LINE_ID,SUM(PO_UNIT_PRICE*QUANTITY) AMOUNT_RECEIVED,SUM(QUANTITY) QUANTITY_RECEIVED
FROM APPS.RCV_TRANSACTIONS GROUP BY PO_HEADER_ID,PO_LINE_ID)
SELECT DISTINCT
PL.PO_LINE_ID AS           INTERFACE_LINE_KEY     ,
PL.PO_HEADER_ID AS INTERFACE_HEADER_KEY,
'ADD' AS ACTION   ,
PL.LINE_NUM AS LINE_NUM ,
(CASE 
WHEN UPPER(APPS.B2C_FNS_PKG.B2C_VALUE_MAPPING('PO_LINES_ALL', 'LINE_TYPE',LT.LINE_TYPE))='MRO-SERVICES' THEN 'Services'
WHEN UPPER(APPS.B2C_FNS_PKG.B2C_VALUE_MAPPING('PO_LINES_ALL', 'LINE_TYPE',LT.LINE_TYPE))='MRO-GOODS' THEN 'Goods'
WHEN UPPER(APPS.B2C_FNS_PKG.B2C_VALUE_MAPPING('PO_LINES_ALL', 'LINE_TYPE',LT.LINE_TYPE)) ='MRO-LEASE'
AND QUANTITY BETWEEN 0 AND 1  THEN 'Services'
WHEN   UPPER(APPS.B2C_FNS_PKG.B2C_VALUE_MAPPING('PO_LINES_ALL', 'LINE_TYPE',LT.LINE_TYPE)) ='MRO-LEASE' 
AND QUANTITY >1  THEN 'Goods'
WHEN  UPPER(APPS.B2C_FNS_PKG.B2C_VALUE_MAPPING('PO_LINES_ALL', 'LINE_TYPE',LT.LINE_TYPE))='MRO-TOOLS' 
AND QUANTITY BETWEEN 0 AND 1  THEN 'Services'
WHEN   UPPER(APPS.B2C_FNS_PKG.B2C_VALUE_MAPPING('PO_LINES_ALL', 'LINE_TYPE',LT.LINE_TYPE)) ='MRO-TOOLS' 
AND QUANTITY >1  THEN 'Goods'
END) AS LINE_TYPE,
PL.ITEM_ID         AS ITEM   ,
REPLACE(CASE  WHEN PL.ITEM_DESCRIPTION LIKE '%,%' OR PL.ITEM_DESCRIPTION LIKE '%"%' 
THEN '"'|| SUBSTR(REPLACE(PL.ITEM_DESCRIPTION, '"', ''''), 1) || '"'
                   ELSE SUBSTR(PL.ITEM_DESCRIPTION, 1) END, CHR(10), ''
    ) AS ITEM_DESCRIPTION      ,
PL.ITEM_REVISION AS    ITEM_REVISION  ,
UPPER(PH.UNSPSC_NAME)   AS CATEGORY  ,
PL.QUANTITY*PL.UNIT_PRICE-nvl(REC.AMOUNT_RECEIVED,0) AS AMOUNT,
PL.QUANTITY-NVL(REC.QUANTITY_RECEIVED,0) AS QUANTITY    ,
APPS.B2C_FNS_PKG.B2C_VALUE_MAPPING('PO_LINES_ALL', 'UNIT_OF_MEASURE',PL.UNIT_MEAS_LOOKUP_CODE) AS UNIT_OF_MEASURE  ,
PL.UNIT_PRICE AS UNIT_PRICE   ,
PL.SECONDARY_QUANTITY   AS   SECONDARY_QUANTITY       ,
PL.SECONDARY_UNIT_OF_MEASURE  AS SECONDARY_UNIT_OF_MEASURE   ,
PL.VENDOR_PRODUCT_NUM  AS VENDOR_PRODUCT_NUM     ,
PL.NEGOTIATED_BY_PREPARER_FLAG  AS NEGOTIATED_BY_PREPARER_FLAG ,
PL.HAZARD_CLASS_ID   AS HAZARD_CLASS,
PL.UN_NUMBER_ID AS UN_NUMBER,
PL.NOTE_TO_VENDOR  AS NOTE_TO_VENDOR ,
NULL AS NOTE_TO_RECEIVER ,
NULL  AS ATTRIBUTE_CATEGORY ,
NULL  AS ATTRIBUTE1 ,
NULL  AS ATTRIBUTE2,
NULL  AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS  ATTRIBUTE16,
NULL AS  ATTRIBUTE17,
NULL AS  ATTRIBUTE18,
NULL AS  ATTRIBUTE19,
NULL AS  ATTRIBUTE20,
NULL AS  ATTRIBUTE_DATE1,
NULL AS  ATTRIBUTE_DATE2,
NULL AS  ATTRIBUTE_DATE3,
NULL AS  ATTRIBUTE_DATE4,
NULL AS  ATTRIBUTE_DATE5,
NULL AS  ATTRIBUTE_DATE6,
NULL AS  ATTRIBUTE_DATE7,
NULL AS  ATTRIBUTE_DATE8,
NULL AS  ATTRIBUTE_DATE9,
NULL AS  ATTRIBUTE_DATE10,
NULL AS  ATTRIBUTE_NUMBER1,
NULL AS  ATTRIBUTE_NUMBER2,
NULL AS  ATTRIBUTE_NUMBER3,
NULL AS  ATTRIBUTE_NUMBER4,
NULL AS  ATTRIBUTE_NUMBER5,
NULL AS  ATTRIBUTE_NUMBER6,
NULL AS  ATTRIBUTE_NUMBER7,
NULL AS  ATTRIBUTE_NUMBER8,
NULL AS  ATTRIBUTE_NUMBER9,
NULL AS  ATTRIBUTE_NUMBER10,
NULL AS  ATTRIBUTE_TIMESTAMP1,
NULL AS  ATTRIBUTE_TIMESTAMP2,
NULL AS  ATTRIBUTE_TIMESTAMP3,
NULL AS  ATTRIBUTE_TIMESTAMP4,
NULL AS  ATTRIBUTE_TIMESTAMP5,
NULL AS  ATTRIBUTE_TIMESTAMP6,
NULL AS  ATTRIBUTE_TIMESTAMP7,
NULL AS  ATTRIBUTE_TIMESTAMP8,
NULL AS  ATTRIBUTE_TIMESTAMP9,
NULL AS  ATTRIBUTE_TIMESTAMP10,
NULL AS  UNIT_WEIGHT,
NULL AS  WEIGHT_UOM_CODE,
NULL AS  WEIGHT_UNIT_OF_MEASURE,
NULL AS  UNIT_VOLUME,   
NULL AS  VOLUME_UOM_CODE, 
NULL AS  VOLUME_UNIT_OF_MEASURE,
NULL AS  TEMPLATE_NAME,   
NULL AS  ITEM_ATTRIBUTE_CATEGORY, 
NULL AS  ITEM_ATTRIBUTE1,
NULL AS  ITEM_ATTRIBUTE2,
NULL AS  ITEM_ATTRIBUTE3,
NULL AS  ITEM_ATTRIBUTE4,
NULL AS  ITEM_ATTRIBUTE5,
NULL AS  ITEM_ATTRIBUTE6,
NULL AS  ITEM_ATTRIBUTE7,
NULL AS  ITEM_ATTRIBUTE8,
NULL AS  ITEM_ATTRIBUTE9,
NULL AS  ITEM_ATTRIBUTE10,
NULL AS  ITEM_ATTRIBUTE11,
NULL AS  ITEM_ATTRIBUTE12,
NULL AS  ITEM_ATTRIBUTE13,
NULL AS  ITEM_ATTRIBUTE14,
NULL AS  ITEM_ATTRIBUTE15,
SYSDATE AS CREATION_DATE,
'TR' AS CREATED_BY,
'N' AS PROCESS_FLAG
FROM APPS.PO_HEADERS_ALL H INNER JOIN  APPS.PO_LINES_ALL PL ON H.PO_HEADER_ID=PL.PO_HEADER_ID
INNER JOIN SMART_HEADER PH ON SUBSTR(PH.PO_ID,1,9)=H.SEGMENT1 AND PH.SL_LINE_NUMBER=PL.LINE_NUM
--INNER JOIN B2C.B2C_P_VENDORS V ON V.VENDOR_ID=H.VENDOR_ID
INNER JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID
LEFT OUTER JOIN RECEIPT REC ON PL.PO_HEADER_ID=REC.PO_HEADER_ID AND PL.PO_LINE_ID=REC.PO_LINE_ID
LEFT JOIN APPS.PO_LINE_TYPES_V LT ON LT.LINE_TYPE_ID=PL.LINE_TYPE_ID
--LEFT JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID 
LEFT JOIN APPS.PO_VENDOR_SITES_ALL VS ON H.VENDOR_SITE_ID||H.VENDOR_ID=VS.VENDOR_SITE_ID||VS.VENDOR_ID
LEFT JOIN APPS.MTL_CATEGORIES MC ON MC.CATEGORY_ID=PL.CATEGORY_ID
WHERE   NVL(H.CLOSED_CODE, '~') <> 'CLOSED'
AND PV.ENABLED_FLAG='Y'
AND PV.END_DATE_ACTIVE IS NULL
AND NVL(PV.VENDOR_TYPE_LOOKUP_CODE,'X') <> 'EXPENSERPT'
AND VS.INACTIVE_DATE IS NULL
AND NVL(VS.RFQ_ONLY_SITE_FLAG,'N')='N'
AND H.SEGMENT1 LIKE 'A%'
AND H.ORG_ID<>'24266' 
--AND h.org_id in (667,25697,23352,24251,166,24246,206,25692,23507)
AND PL.QUANTITY*PL.UNIT_PRICE-NVL(REC.AMOUNT_RECEIVED,0)>0
AND MONTHS_BETWEEN(SYSDATE,H.CREATION_DATE)<=18;