TRUNCATE TABLE B2C.PO_LINE_LOCATIONS_INTERFACE;
INSERT INTO B2C.PO_LINE_LOCATIONS_INTERFACE
WITH SMART_HEADER AS(
SELECT * FROM
(SELECT DENSE_RANK() OVER(PARTITION BY SUBSTR(H.PO_ID,1,9) ORDER BY H.PO_ID DESC) RNK,H.*,SL.PO_ID SL_PO_ID,SL.LINE_NUMBER SL_LINE_NUMBER,
SL.REQUESTOR_SHIPTO SL_REQUESTOR_SHIPTO,SL.NEED_BY_DATE SL_NEED_BY_DATE,H.SHIP_TO_LOCATION H_SHIP_TO_LOCATION,
(CASE WHEN H.SHIP_TO_LOCATION LIKE 'AD%'  THEN U.LOCATION
      ELSE H.SHIP_TO_LOCATION END) SL_LOCATION 
FROM SMARTSTG.SMARTOUTBOUNDPOHEADER@SMART_DATA H INNER JOIN SMARTSTG.SMARTOUTBOUNDPOLINE@SMART_DATA SL ON H.PO_ID=SL.PO_ID
LEFT JOIN SMARTSTG.USER_PROFILE_HOLD@SMART_DATA U ON H.REQUESTOR_UNIQUENAME=U.FULL_NAME
WHERE  H.WM_PROCESS_FLAG='C')
WHERE RNK=1),
RECEIPT AS 
(SELECT PO_HEADER_ID,PO_LINE_ID,PO_LINE_LOCATION_ID,SUM(PO_UNIT_PRICE*QUANTITY) AMOUNT_RECEIVED,SUM(QUANTITY) QUANTITY_RECEIVED
FROM APPS.RCV_TRANSACTIONS GROUP BY PO_HEADER_ID,PO_LINE_ID,PO_LINE_LOCATION_ID)
SELECT DISTINCT 
LL.LINE_LOCATION_ID AS INTERFACE_LINE_LOCATION_KEY   ,
LL.PO_LINE_ID AS INTERFACE_LINE_KEY    ,
LL.SHIPMENT_NUM AS SHIPMENT_NUM    ,
APPS.B2C_FNS_PKG.B2C_value_mapping('PURCHASE ORDERS', 'LOCATIONS',NVL(SH.SL_LOCATION,SH.H_SHIP_TO_LOCATION)) AS SHIP_TO_LOCATION   ,
APPS.B2C_FNS_PKG.B2C_value_mapping('PURCHASE ORDERS', 'SHIP_TO_ORGANIZATION_CODE', OU.NAME) AS SHIP_TO_ORGANIZATION_CODE,
PL.QUANTITY*PL.UNIT_PRICE-NVL(REC.AMOUNT_RECEIVED,0) AS AMOUNT  ,
LL.QUANTITY-NVL(REC.QUANTITY_RECEIVED,0) AS QUANTITY,
NVL(TO_CHAR(LL.NEED_BY_DATE,'YYYY/MM/DD'),TO_CHAR(SH.SL_NEED_BY_DATE,'YYYY/MM/DD')) AS NEED_BY_DATE  ,
TO_CHAR(LL.PROMISED_DATE,'YYYY/MM/DD')  AS PROMISED_DATE ,
LL.SECONDARY_QUANTITY      AS SECONDARY_QUANTITY     ,
LL.SECONDARY_UNIT_OF_MEASURE       AS SECONDARY_UNIT_OF_MEASURE      ,
'EXPENSE' AS DESTINATION_TYPE_CODE,
LL.ACCRUE_ON_RECEIPT_FLAG,
LL.ALLOW_SUBSTITUTE_RECEIPTS_FLAG AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
NULL AS ASSESSABLE_VALUE   ,
LL.DAYS_EARLY_RECEIPT_ALLOWED  AS DAYS_EARLY_RECEIPT_ALLOWED ,
LL.DAYS_LATE_RECEIPT_ALLOWED         AS DAYS_LATE_RECEIPT_ALLOWED        ,
LL.ENFORCE_SHIP_TO_LOCATION_CODE           AS ENFORCE_SHIP_TO_LOCATION_CODE          ,
LL.INSPECTION_REQUIRED_FLAG  AS INSPECTION_REQUIRED_FLAG ,
LL.RECEIPT_REQUIRED_FLAG        AS RECEIPT_REQUIRED_FLAG       ,
LL.INVOICE_CLOSE_TOLERANCE AS INVOICE_CLOSE_TOLERANCE,
LL.RECEIVE_CLOSE_TOLERANCE  AS RECEIVE_CLOSE_TOLERANCE ,
LL.QTY_RCV_TOLERANCE   AS QTY_RCV_TOLERANCE  ,
LL.QTY_RCV_EXCEPTION_CODE           AS QTY_RCV_EXCEPTION_CODE          ,
LL.RECEIPT_DAYS_EXCEPTION_CODE         AS RECEIPT_DAYS_EXCEPTION_CODE        ,
(CASE WHEN LL.RECEIVING_ROUTING_ID=1 THEN 'Standard receipt'
		WHEN LL.RECEIVING_ROUTING_ID=2 THEN 'Inspection required'
		WHEN LL.RECEIVING_ROUTING_ID=3 THEN 'Direct delivery' END) AS RECEIVING_ROUTING,
LL.NOTE_TO_RECEIVER          AS NOTE_TO_RECEIVER         ,
NULL AS INPUT_TAX_CLASSIFICATION_CODE,
NULL AS LINE_INTENDED_USE,
NULL AS PRODUCT_CATEGORY ,
NULL AS PRODUCT_FISC_CLASSIFICATION,
PL.PURCHASE_BASIS AS PRODUCT_TYPE,
NULL AS TRX_BUSINESS_CATEGORY     ,
NULL AS USER_DEFINED_FISC_CLASS ,
NULL   AS ATTRIBUTE_CATEGORY  ,
NULL AS ATTRIBUTE1   ,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE18,
NULL AS ATTRIBUTE19,
NULL AS ATTRIBUTE20,
NULL AS ATTRIBUTE_DATE1,
NULL AS ATTRIBUTE_DATE2,
NULL AS ATTRIBUTE_DATE3,
NULL AS ATTRIBUTE_DATE4,
NULL AS ATTRIBUTE_DATE5,
NULL AS ATTRIBUTE_DATE6,
NULL AS ATTRIBUTE_DATE7,
NULL AS ATTRIBUTE_DATE8,
NULL AS ATTRIBUTE_DATE9,
NULL AS ATTRIBUTE_DATE10,
NULL AS ATTRIBUTE_NUMBER1,
NULL AS ATTRIBUTE_NUMBER2,
NULL AS ATTRIBUTE_NUMBER3,
NULL AS ATTRIBUTE_NUMBER4,
NULL AS ATTRIBUTE_NUMBER5,
NULL AS ATTRIBUTE_NUMBER6,
NULL AS ATTRIBUTE_NUMBER7,
NULL AS ATTRIBUTE_NUMBER8,
NULL AS ATTRIBUTE_NUMBER9,
NULL AS ATTRIBUTE_NUMBER10,
NULL AS ATTRIBUTE_TIMESTAMP1,
NULL AS ATTRIBUTE_TIMESTAMP2,
NULL AS ATTRIBUTE_TIMESTAMP3,
NULL AS ATTRIBUTE_TIMESTAMP4,
NULL AS ATTRIBUTE_TIMESTAMP5,
NULL AS ATTRIBUTE_TIMESTAMP6,
NULL AS ATTRIBUTE_TIMESTAMP7,
NULL AS ATTRIBUTE_TIMESTAMP8,
NULL AS ATTRIBUTE_TIMESTAMP9,
NULL AS ATTRIBUTE_TIMESTAMP10,
NULL AS FREIGHT_CARRIER ,
NULL AS MODE_OF_TRANSPORT ,
NULL AS SERVICE_LEVEL ,
NULL AS FINAL_DISCHARGE_LOCATION_CODE,
NULL AS REQUESTED_SHIP_DATE    ,
NULL AS PROMISED_SHIP_DATE ,
NULL AS REQUESTED_DELIVERY_DATE,
NULL AS PROMISED_DELIVERY_DATE,
SYSDATE AS CREATION_DATE,
'TR' AS CREATED_BY,
'N' AS PROCESS_FLAG
FROM 
APPS.PO_LINE_LOCATIONS_ALL LL
INNER JOIN APPS.PO_LINES_ALL PL ON LL.PO_LINE_ID=PL.PO_LINE_ID AND LL.PO_HEADER_ID=PL.PO_HEADER_ID 
INNER JOIN APPS.PO_HEADERS_ALL H ON PL.PO_HEADER_ID=H.PO_HEADER_ID
INNER JOIN SMART_HEADER  SH ON SUBSTR(SH.PO_ID,1,9)=H.SEGMENT1 AND SH.SL_LINE_NUMBER=PL.LINE_NUM
--INNER JOIN B2C.B2C_P_VENDORS V ON V.VENDOR_ID=H.VENDOR_ID
INNER JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID
LEFT OUTER JOIN RECEIPT REC ON REC.PO_LINE_LOCATION_ID=LL.LINE_LOCATION_ID AND REC.PO_LINE_ID=LL.PO_LINE_ID AND
REC.PO_HEADER_ID=LL.PO_HEADER_ID
--LEFT JOIN APPS.PO_VENDORS PV ON H.VENDOR_ID=PV.VENDOR_ID
LEFT JOIN APPS.PO_VENDOR_SITES_ALL VS ON H.VENDOR_SITE_ID||H.VENDOR_ID=VS.VENDOR_SITE_ID||VS.VENDOR_ID
LEFT JOIN APPS.HR_ALL_ORGANIZATION_UNITS OU ON H.ORG_ID=OU.ORGANIZATION_ID
--LEFT JOIN AP.AP_TAX_CODES_ALL TX ON LL.TAX_CODE_ID=TX.TAX_ID
WHERE NVL(H.CLOSED_CODE, '~') <> 'CLOSED'
AND PV.ENABLED_FLAG='Y'
AND PV.END_DATE_ACTIVE IS NULL
AND NVL(PV.VENDOR_TYPE_LOOKUP_CODE,'X') <> 'EXPENSERPT'
AND VS.INACTIVE_DATE IS NULL
AND NVL(VS.RFQ_ONLY_SITE_FLAG,'N')='N'
AND H.SEGMENT1 LIKE 'A%'
AND H.ORG_ID<>'24266'
--AND h.org_id in ( 667,25697,23352,24251,166,24246,206,25692,23507)
AND PL.QUANTITY*PL.UNIT_PRICE-NVL(REC.AMOUNT_RECEIVED,0)>0
AND MONTHS_BETWEEN(SYSDATE,H.CREATION_DATE)<=18;